server:
  port: 8989
  context-path: /test-spring-boot-2
  jsp-servlet:
    init-parameters:
      development: true
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  mvc:
    view:
      prefix: /
      suffix: .jsp

    multipart:
      max-file-size: 10MB
      max-request-size: 200MB
  http:
    encoding:
      charset: UTF-8
      force: true
mybatis:
  type-aliases-package: com.chenxi.entity
  mapper-locations: classpath:com/chenxi/mapper/*Mapper.xml
